#!/bin/zsh

## Setup Prezto

rm -f ${ZDOTDIR:-$HOME}/{.zlogin,.zlogout,.zpreztorc,.zprofile,.zshenv,.zshrc}
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done
